# Имя workflow (будет видно в GitHub Actions)
name: Main Taski Workflow

# Триггер — когда запускать
on:
  push:
    branches:
      - main

# Список задач
jobs:
  checkout-and-print-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Print project tree
        run: tree .
